apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loruceanro-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: loruceanro.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: loruceanro-frontend
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loruceanro-frontend
                port:
                  number: 80
