apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rpi-prod
resources:
  - loruceanro

replicas:
  - name: loruceanro-user-service
    count: 3
  - name: loruceanro-catalog-service
    count: 3
  - name: loruceanro-order-service
    count: 3
  - name: loruceanro-frontend
    count: 2
