apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rpi-prod
resources:
  - frontend
  - loruceanro

images:
  - name: nginx
    newTag: 1.25-alpine
  - name: myregistry/user-service
    newTag: "1.0.0"
  - name: myregistry/catalog-service
    newTag: "1.0.0"
  - name: myregistry/order-service
    newTag: "1.0.0"
  - name: myregistry/frontend
    newTag: "1.0.0"

replicas:
  - name: frontend
    count: 1
  - name: user-service
    count: 3
  - name: catalog-service
    count: 3
  - name: order-service
    count: 3
  - name: loruceanro-frontend
    count: 2
