# Сгенерируй с помощью kubeseal (namespace = rpi-dev):
#   kubectl create secret generic db-secrets -n rpi-dev \
#     --from-literal=users-db-url='...' \
#     --from-literal=catalog-db-url='...' \
#     --from-literal=orders-db-url='...' \
#     --from-literal=jwt-secret='...' \
#     --from-literal=postgres-pass='...' \
#     --from-literal=redis-url='...' \
#     --dry-run=client -o yaml | \
#   kubeseal --controller-namespace sealed-secrets --format yaml > sealed-secret.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secrets
  namespace: rpi-dev
spec:
  encryptedData:
    users-db-url: PLACEHOLDER
    catalog-db-url: PLACEHOLDER
    orders-db-url: PLACEHOLDER
    jwt-secret: PLACEHOLDER
    postgres-pass: PLACEHOLDER
    redis-url: PLACEHOLDER
  template:
    metadata:
      name: db-secrets
      namespace: rpi-dev
