apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
spec:
  destination:
    namespace: rpi-infra
    server: https://kubernetes.default.svc
  source:
    path: infra
    repoURL: https://github.com/beatplugg/gitops
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true
